version: '3.1'
services:
  db:
    image: postgres:12-alpine
    env_file:
      - .env
    ports:
      - 5416:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /db/postgresql-12:/var/lib/postgresql/data

volumes:
  postgres_data:
