version: '3.1'
services:
  db:
    image: postgres:9.6.23-alpine3.14
    env_file:
      - .env
    ports:
      - 5416:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /db/data-dime-user-auth:/var/lib/postgresql/data

volumes:
  postgres_data:
